Migrering til ds-react
navikt/tilbakemeldinger pull request #570
Opened 2023-01-12 09:38 UTC by bjornhun

2023-01-12 10:14 UTC, macbruker reviewed
Så gjennom kjapt og fant noen småting på styling og markup. JS/React-biten overlater jeg til andre å vurdere ☺️

2023-01-12 10:14 UTC, macbruker commented on src/components/takk/Takk.tsx
> +      </Link>
Hva blir rendret HTML her? Det er ikke gyldig markup med `<button>` inni `<a>`.

2023-01-12 10:14 UTC, macbruker commented on src/components/tilbakeknapp/Tilbakeknapp.tsx
> +    </Button>
Dette er riktig løsning for lenker som skal ha styling så de ser ut som knapper.

2023-01-12 10:14 UTC, macbruker commented on src/pages/tilbakemeldinger/feil-og-mangler/FeilOgMangler.tsx
> +                    </Button>
Det finnes en egen variant av `<Button>` med prop `loading` som kanskje kan brukes her. https://aksel.nav.no/komponenter/core/button#ha8bb240d2c68

2023-01-12 12:40 UTC, PerOlavM requested changes

2023-01-12 13:18 UTC, bjornhun commented on src/components/lenkepanel/Lenkepanel.less
> +    box-sizing: content-box;
Fikset

2023-01-12 13:18 UTC, bjornhun commented on src/components/takk/Takk.tsx
> +      </Link>
Fikset

2023-01-12 13:18 UTC, bjornhun commented on src/pages/tilbakemeldinger/feil-og-mangler/FeilOgMangler.tsx
> +                    </Button>
Fikset

2023-01-12 13:19 UTC, bjornhun commented on src/components/input-fields/SelectEnhet.tsx
> +      <Label as={"p"}>
Vet ikke helt hvordan det skjedde, men fikset

2023-01-12 13:19 UTC, bjornhun commented on src/components/input-fields/SelectEnhet.tsx
> +import { ErrorMessage, Label, Loader } from "@navikt/ds-react";
Fikset

2023-01-12 13:20 UTC, bjornhun commented on src/App.tsx
Mister all ds-styling om jeg fjerner denne importen

2023-01-12 13:52 UTC, bjornhun commented on src/components/input-fields/EnhetCombobox.tsx
> +        style={
Helt enig. Til mitt forsvar er dette gammel kode som jeg har refaktorert, men greit å få det fikset. Skrev det om nå, ta gjerne en titt og se om det ser ok ut!

2023-01-12 14:16 UTC, macbruker commented on src/components/input-fields/EnhetCombobox.tsx
> +        style={
Til sitt bruk, er inline styles helt ok, synes jeg. Det kommer an på oppgaven 😅

2023-01-12 14:32 UTC, macbruker approved these changes

2023-01-12 14:33 UTC, bjornhun commented on src/App.tsx
Fjernet importen i index.less og importerer kun i app.tsx i henhold til dok: https://aksel.nav.no/grunnleggende/guider/kom-i-gang-som-utvikler

Da ble vi kvitt en feilmelding i console også.

2023-01-13 14:01 UTC, macbruker approved these changes

2023-01-13 14:14 UTC, macbruker commented on src/App.less
> +.navds-guide-panel.navds-guide-panel--poster {
Alternativt går det an å bare doble klassen for å øke specificity score. `.navds-guide-panel.navds-guide-panel`

2023-01-16 11:08 UTC, merged